// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIcEMpU7dq9GS4XxJmjtbzM4C5l8lo28',
    appId: '1:613266403122:web:7c38a03c313c898799712b',
    messagingSenderId: '613266403122',
    projectId: 'berkflutterfirebase',
    authDomain: 'berkflutterfirebase.firebaseapp.com',
    storageBucket: 'berkflutterfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLL4cLiQg2YbrSq3kDcOCo4R4DVOlT8Q',
    appId: '1:613266403122:android:972c01602f34e86799712b',
    messagingSenderId: '613266403122',
    projectId: 'berkflutterfirebase',
    storageBucket: 'berkflutterfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw47FSciVEMoNNFVFxwPK1AeiQuxnAZhM',
    appId: '1:613266403122:ios:edf38549ea0d3fbe99712b',
    messagingSenderId: '613266403122',
    projectId: 'berkflutterfirebase',
    storageBucket: 'berkflutterfirebase.appspot.com',
    iosBundleId: 'com.example.telefonRehberi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw47FSciVEMoNNFVFxwPK1AeiQuxnAZhM',
    appId: '1:613266403122:ios:edf38549ea0d3fbe99712b',
    messagingSenderId: '613266403122',
    projectId: 'berkflutterfirebase',
    storageBucket: 'berkflutterfirebase.appspot.com',
    iosBundleId: 'com.example.telefonRehberi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPIcEMpU7dq9GS4XxJmjtbzM4C5l8lo28',
    appId: '1:613266403122:web:727b059ee8fe3dd399712b',
    messagingSenderId: '613266403122',
    projectId: 'berkflutterfirebase',
    authDomain: 'berkflutterfirebase.firebaseapp.com',
    storageBucket: 'berkflutterfirebase.appspot.com',
  );
}
